# Generated by Django 3.1.2 on 2020-11-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neibour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='emergency',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hood_pic',
            new_name='hood_logo',
        ),
    ]
