# Generated by Django 3.1.2 on 2020-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neibour', '0002_auto_20201102_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
